import type { Worktree } from '../src/types.js';

export const makeWorktree = (overrides: Partial<Worktree> = {}): Worktree => ({
  path: '/tmp/repo/wt',
  head: '0'.repeat(40),
  branch: 'feature/x',
  bare: false,
  detached: false,
  locked: false,
  lockReason: null,
  prunable: false,
  prunableReason: null,
  isMain: false,
  isCurrent: false,
  missing: false,
  lastCommitAt: '2025-06-01T00:00:00.000Z',
  checkoutAt: '2025-06-02T00:00:00.000Z',
  createdAt: '2025-06-03T00:00:00.000Z',
  dirty: false,
  unpushed: null,
  mergedIntoDefault: false,
  sizeKb: null,
  pr: { status: 'none' },
  ...overrides,
});
